GET http://localhost:8787/api/test
Accept: application/json

###


###

POST http://localhost:8787/api/item/create
Content-Type: application/json

{
  "id": "123",
  "name": "testItem1",
  "price": 123.12
}

###